server:
  port: 8881
  servlet:
    context-path: /order-service

spring:
  application:
    name: order-service
  
  # RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:cy}
    password: ${RABBITMQ_PASSWORD:123456}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:cy}
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 5
        prefetch: 10
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 2

# WebSocket配置
websocket:
  heartbeat-timeout: 300000
  cleanup-interval: 60000

  # 异步任务配置
  task:
    execution:
      pool:
        core-size: 5
        max-size: 20
        queue-capacity: 100
        keep-alive: 60s

# 日志配置
logging:
  level:
    root: INFO
    com.cy.order: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 应用配置
order:
  service:
    notification:
      enabled: true
      retry-count: 3
      retry-interval: 5000

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}