server:
  port: 8083
  servlet:
    context-path: /crm-service

spring:
  application:
    name: crm-service
  
  # RabbitMQ配置
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:cy}
    password: ${RABBITMQ_PASSWORD:123456}
    virtual-host: ${RABBITMQ_VIRTUAL_HOST:cy}
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 3
        prefetch: 5
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 2

# 日志配置
logging:
  level:
    root: INFO
    com.cy.crm: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
    file: '%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'

# 应用配置
crm:
  service:
    cache:
      enabled: true
      expire-minutes: 60
    batch:
      size: 100
      interval-seconds: 300

# 监控配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when_authorized
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: ${spring.application.name}